<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name' => 'الفاتحة', 'ayah_count' => 7],
            ['number' => 2, 'name' => 'البقرة', 'ayah_count' => 286],
            ['number' => 3, 'name' => 'آل عمران', 'ayah_count' => 200],
            ['number' => 4, 'name' => 'النساء', 'ayah_count' => 176],
            ['number' => 5, 'name' => 'المائدة', 'ayah_count' => 120],
            ['number' => 6, 'name' => 'الأنعام', 'ayah_count' => 165],
            ['number' => 7, 'name' => 'الأعراف', 'ayah_count' => 206],
            ['number' => 8, 'name' => 'الأنفال', 'ayah_count' => 75],
            ['number' => 9, 'name' => 'التوبة', 'ayah_count' => 129],
            ['number' => 10, 'name' => 'يونس', 'ayah_count' => 109],
            ['number' => 11, 'name' => 'هود', 'ayah_count' => 123],
            ['number' => 12, 'name' => 'يوسف', 'ayah_count' => 111],
            ['number' => 13, 'name' => 'الرعد', 'ayah_count' => 43],
            ['number' => 14, 'name' => 'إبراهيم', 'ayah_count' => 52],
            ['number' => 15, 'name' => 'الحجر', 'ayah_count' => 99],
            ['number' => 16, 'name' => 'النحل', 'ayah_count' => 128],
            ['number' => 17, 'name' => 'الإسراء', 'ayah_count' => 111],
            ['number' => 18, 'name' => 'الكهف', 'ayah_count' => 110],
            ['number' => 19, 'name' => 'مريم', 'ayah_count' => 98],
            ['number' => 20, 'name' => 'طه', 'ayah_count' => 135],
            ['number' => 21, 'name' => 'الأنبياء', 'ayah_count' => 112],
            ['number' => 22, 'name' => 'الحج', 'ayah_count' => 78],
            ['number' => 23, 'name' => 'المؤمنون', 'ayah_count' => 118],
            ['number' => 24, 'name' => 'النور', 'ayah_count' => 64],
            ['number' => 25, 'name' => 'الفرقان', 'ayah_count' => 77],
            ['number' => 26, 'name' => 'الشعراء', 'ayah_count' => 227],
            ['number' => 27, 'name' => 'النمل', 'ayah_count' => 93],
            ['number' => 28, 'name' => 'القصص', 'ayah_count' => 88],
            ['number' => 29, 'name' => 'العنكبوت', 'ayah_count' => 69],
            ['number' => 30, 'name' => 'الروم', 'ayah_count' => 60],
            ['number' => 31, 'name' => 'لقمان', 'ayah_count' => 34],
            ['number' => 32, 'name' => 'السجدة', 'ayah_count' => 30],
            ['number' => 33, 'name' => 'الأحزاب', 'ayah_count' => 73],
            ['number' => 34, 'name' => 'سبأ', 'ayah_count' => 54],
            ['number' => 35, 'name' => 'فاطر', 'ayah_count' => 45],
            ['number' => 36, 'name' => 'يس', 'ayah_count' => 83],
            ['number' => 37, 'name' => 'الصافات', 'ayah_count' => 182],
            ['number' => 38, 'name' => 'ص', 'ayah_count' => 88],
            ['number' => 39, 'name' => 'الزمر', 'ayah_count' => 75],
            ['number' => 40, 'name' => 'غافر', 'ayah_count' => 85],
            ['number' => 41, 'name' => 'فصلت', 'ayah_count' => 54],
            ['number' => 42, 'name' => 'الشورى', 'ayah_count' => 53],
            ['number' => 43, 'name' => 'الزخرف', 'ayah_count' => 89],
            ['number' => 44, 'name' => 'الدخان', 'ayah_count' => 59],
            ['number' => 45, 'name' => 'الجاثية', 'ayah_count' => 37],
            ['number' => 46, 'name' => 'الأحقاف', 'ayah_count' => 35],
            ['number' => 47, 'name' => 'محمد', 'ayah_count' => 38],
            ['number' => 48, 'name' => 'الفتح', 'ayah_count' => 29],
            ['number' => 49, 'name' => 'الحجرات', 'ayah_count' => 18],
            ['number' => 50, 'name' => 'ق', 'ayah_count' => 45],
            ['number' => 51, 'name' => 'الذاريات', 'ayah_count' => 60],
            ['number' => 52, 'name' => 'الطور', 'ayah_count' => 49],
            ['number' => 53, 'name' => 'النجم', 'ayah_count' => 62],
            ['number' => 54, 'name' => 'القمر', 'ayah_count' => 55],
            ['number' => 55, 'name' => 'الرحمن', 'ayah_count' => 78],
            ['number' => 56, 'name' => 'الواقعة', 'ayah_count' => 96],
            ['number' => 57, 'name' => 'الحديد', 'ayah_count' => 29],
            ['number' => 58, 'name' => 'المجادلة', 'ayah_count' => 22],
            ['number' => 59, 'name' => 'الحشر', 'ayah_count' => 24],
            ['number' => 60, 'name' => 'الممتحنة', 'ayah_count' => 13],
            ['number' => 61, 'name' => 'الصف', 'ayah_count' => 14],
            ['number' => 62, 'name' => 'الجمعة', 'ayah_count' => 11],
            ['number' => 63, 'name' => 'المنافقون', 'ayah_count' => 11],
            ['number' => 64, 'name' => 'التغابن', 'ayah_count' => 18],
            ['number' => 65, 'name' => 'الطلاق', 'ayah_count' => 12],
            ['number' => 66, 'name' => 'التحريم', 'ayah_count' => 12],
            ['number' => 67, 'name' => 'الملك', 'ayah_count' => 30],
            ['number' => 68, 'name' => 'القلم', 'ayah_count' => 52],
            ['number' => 69, 'name' => 'الحاقة', 'ayah_count' => 52],
            ['number' => 70, 'name' => 'المعارج', 'ayah_count' => 44],
            ['number' => 71, 'name' => 'نوح', 'ayah_count' => 28],
            ['number' => 72, 'name' => 'الجن', 'ayah_count' => 28],
            ['number' => 73, 'name' => 'المزمل', 'ayah_count' => 20],
            ['number' => 74, 'name' => 'المدثر', 'ayah_count' => 56],
            ['number' => 75, 'name' => 'القيامة', 'ayah_count' => 40],
            ['number' => 76, 'name' => 'الإنسان', 'ayah_count' => 31],
            ['number' => 77, 'name' => 'المرسلات', 'ayah_count' => 50],
            ['number' => 78, 'name' => 'النبأ', 'ayah_count' => 40],
            ['number' => 79, 'name' => 'النازعات', 'ayah_count' => 46],
            ['number' => 80, 'name' => 'عبس', 'ayah_count' => 42],
            ['number' => 81, 'name' => 'التكوير', 'ayah_count' => 29],
            ['number' => 82, 'name' => 'الانفطار', 'ayah_count' => 19],
            ['number' => 83, 'name' => 'المطففين', 'ayah_count' => 36],
            ['number' => 84, 'name' => 'الانشقاق', 'ayah_count' => 25],
            ['number' => 85, 'name' => 'البروج', 'ayah_count' => 22],
            ['number' => 86, 'name' => 'الطارق', 'ayah_count' => 17],
            ['number' => 87, 'name' => 'الأعلى', 'ayah_count' => 19],
            ['number' => 88, 'name' => 'الغاشية', 'ayah_count' => 26],
            ['number' => 89, 'name' => 'الفجر', 'ayah_count' => 30],
            ['number' => 90, 'name' => 'البلد', 'ayah_count' => 20],
            ['number' => 91, 'name' => 'الشمس', 'ayah_count' => 15],
            ['number' => 92, 'name' => 'الليل', 'ayah_count' => 21],
            ['number' => 93, 'name' => 'الضحى', 'ayah_count' => 11],
            ['number' => 94, 'name' => 'الشرح', 'ayah_count' => 8],
            ['number' => 95, 'name' => 'التين', 'ayah_count' => 8],
            ['number' => 96, 'name' => 'العلق', 'ayah_count' => 19],
            ['number' => 97, 'name' => 'القدر', 'ayah_count' => 5],
            ['number' => 98, 'name' => 'البينة', 'ayah_count' => 8],
            ['number' => 99, 'name' => 'الزلزلة', 'ayah_count' => 8],
            ['number' => 100, 'name' => 'العاديات', 'ayah_count' => 11],
            ['number' => 101, 'name' => 'القارعة', 'ayah_count' => 11],
            ['number' => 102, 'name' => 'التكاثر', 'ayah_count' => 8],
            ['number' => 103, 'name' => 'العصر', 'ayah_count' => 3],
            ['number' => 104, 'name' => 'الهمزة', 'ayah_count' => 9],
            ['number' => 105, 'name' => 'الفيل', 'ayah_count' => 5],
            ['number' => 106, 'name' => 'قريش', 'ayah_count' => 4],
            ['number' => 107, 'name' => 'الماعون', 'ayah_count' => 7],
            ['number' => 108, 'name' => 'الكوثر', 'ayah_count' => 3],
            ['number' => 109, 'name' => 'الكافرون', 'ayah_count' => 6],
            ['number' => 110, 'name' => 'النصر', 'ayah_count' => 3],
            ['number' => 111, 'name' => 'المسد', 'ayah_count' => 5],
            ['number' => 112, 'name' => 'الإخلاص', 'ayah_count' => 4],
            ['number' => 113, 'name' => 'الفلق', 'ayah_count' => 5],
            ['number' => 114, 'name' => 'الناس', 'ayah_count' => 6],
        ];

        Surah::insert($surahs);
    }
}
